### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by ronen** [SchemaPlus/schema_plus#188]
Now that rails 4.2 is out, get the final kinks out of the 4.2 branch.

Opening this issue since PRs #175 and #186 with discussion of 4.2 development are closed.

**Comment by donv** [comment]
Getting JRuby to work with ActiveRecord 4.2 is a much bigger job than I thought.  It will take a while, and could be tracked in a separate issue.

**Comment by ronen** [comment]
@donv 
> Getting JRuby to work with ActiveRecord 4.2 is a much bigger job than I thought.

Bummer, I hoped it was already pretty close in the 1.x branch (given the work done by @bacrossland in #173).  

> could be tracked in a separate issue.

sure, go ahead and open one!

**Comment by bacrossland** [comment]
That is a bummer. When last I dove into the 1.x branch, the tests for JRuby only failed on AR 4.0. AR 4.1 passed as did AR 3.2. I had changed nothing in my gem setup just switching between AR versions. Digging into that it turns out that the failure is due to changes in AR 4.0 that were fixed in AR 4.1. So the 1.x branch with the #173 fix supported JRuby in all AR versions except 4.0. 

@donv I'm interested in seeing that issue opened and hearing about what you've already discovered.

**Comment by ronen** [comment]
In case any of you are interested, I had a few spare moments today so I cleaned up the master branch more.  it's now at 100% code coverage.

**Comment by donv** [comment]
Great!

@ronen @bacrossland I started looking at getting ARJDBC working with AR4.2 without schema_plus, and I found and fixed some things, but it is a big gem to wade through, and I got discouraged and dropped it.  I will pick it up at some point, I am sure, but for now I am working on other projects.

The issue to track ARJDBC+AR42 support is here:  https://github.com/jruby/activerecord-jdbc-adapter/issues/599

Would be nice to make progress there.

**Comment by ronen** [comment]
started  [C].  see the `refactor` branch

**Comment by donv** [comment]
Woohoo! Great!

**Comment by bacrossland** [comment]
Nice!

**Comment by ronen** [comment]
Closing this out to move discussion to #197.  Feedback welcome!
