### ISSUE TITLE
Multiple indices on same column are ignored when loading schema on Postgres

### ISSUE THREAD

**Issue by thmzlt** [SchemaPlus/schema_plus#196]
When adding a table index with the same column of a foreign key index created by `schema_plus` (i.e. two indices on the same column with different names), loading the schema will ignore the first index declared in the `create_table` block for the table.

_[This is on OS X 10.9, Postgres 9.3.5 and Ruby 2.1.5]_

I have a [test Rails application](https://github.com/thmzlt/test_app) you can use to reproduce the problem. Clone the repo on the `index` branch, create the database, and try loading and then dumping the schema. (I used `rake db:drop db:create db:schema:load db:schema:dump`.)

The following diff comes up:
```diff
diff --git a/db/schema.rb b/db/schema.rb
index c2bbaf7..2cdbfff 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -28,7 +28,6 @@ ActiveRecord::Schema.define(version: 20150115174027) do
     t.integer "airplane_id"
     t.integer "pilot_id"
     t.index ["airplane_id"], :name => "fk__airplanes_pilots_airplane_id"
-    t.index ["pilot_id"], :name => "fk__airplanes_pilots_pilot_id"
     t.index ["pilot_id"], :name => "index_airplanes_pilots_on_pilot_id", :unique => true
     t.foreign_key ["airplane_id"], "airplanes", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_airplanes_pilots_airplane_id"
     t.foreign_key ["pilot_id"], "pilots", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_airplanes_pilots_pilot_id"
```

If you manually change the order of the two indices on `pilot_id`, and load & dump the schema, then the diff becomes:

```diff
diff --git a/db/schema.rb b/db/schema.rb
index c2bbaf7..749bd9d 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -29,7 +29,6 @@ ActiveRecord::Schema.define(version: 20150115174027) do
     t.integer "pilot_id"
     t.index ["airplane_id"], :name => "fk__airplanes_pilots_airplane_id"
     t.index ["pilot_id"], :name => "fk__airplanes_pilots_pilot_id"
-    t.index ["pilot_id"], :name => "index_airplanes_pilots_on_pilot_id", :unique => true
     t.foreign_key ["airplane_id"], "airplanes", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_airplanes_pilots_airplane_id"
     t.foreign_key ["pilot_id"], "pilots", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_airplanes_pilots_pilot_id"
   end
```

**Comment by fj** [comment]
:+1:, I have this issue too.

The expected `schema_plus` behavior for me is that the schema does not have a diff after loading and dumping.

**Comment by ronen** [comment]
@thmzlt thanks for (yet another!) detailed bug report.

This is arguably a bug in rails:  `t.index` only handles one index per column, see https://github.com/rails/rails/blob/4-1-stable/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L238. It's tickled by schema_plus though, because rails' schema dumper defines indexes using `add_index` outside the `create_table` block, whereas schema_plus tidies the dump by defining them using `t.index`. 

That said, it's probably bad form to have two indexes on the same field anyway; the database will be doing extra unneeded work to maintain them both.  No?

The reason you're getting two is that in your migration
```ruby
create_table :airplanes_pilots do |t|
   t.references :airplane
   t.references :pilot
end
add_index :airplanes_pilots, [:pilot_id], unique: true
```
schema_plus (by default) auto-creates an index for the foreign key constraint; and the add_index statement creates a second one.  In order to get just one index and have it be unique, you can do:

```ruby
create_table :airplanes_pilots do |t|
   t.references :airplane
   t.references :pilot, index: { unique: true }    # or just index: :unique
end
```

I could fix the bug by having schema_plus dump the extra indexes for a column using `add_index` outside the block.  But since this seems like a bug only when doing something that probably shouldn't be done, and there's another way to achieve the result you want, I'm thinking I'll let this slide.

**Comment by ronen** [comment]
FWIW this is fixed in the [schema_plus](https://github.com/SchemaPlus/schema_plus) 2.0 prerelease, i.e. in the new [schema_plus_indexes](https://github.com/SchemaPlus/schema_plus_indexes) gem.

**Comment by fj** [comment]
Thanks @ronen!
