### ISSUE TITLE
Rails 4.2/Postgres 9.4 + Devise cannot login with schema_plus enabled

### ISSUE THREAD

**Issue by lawso017** [SchemaPlus/schema_plus#198]
I'm troubleshooting an odd error encountered when logging in to a Devise-enabled app running Rails 4.2.0 + Postgres 9.4 + SchemaPlus 1.8.4.

Am receiving a message:

````
NoMethodError in SessionsController#create
undefined method `to_i' for #<SchemaPlus::ActiveRecord::DbDefault:0x007fb053100800>
````

A stack excerpt is as follows:

````
/Users/w/.rbenv/versions/2.2.0/lib/ruby/2.2.0/ipaddr.rb:471:in `initialize'
/Users/w/.rbenv/versions/2.2.0/lib/ruby/2.2.0/ipaddr.rb:516:in `new'
/Users/w/.rbenv/versions/2.2.0/lib/ruby/2.2.0/ipaddr.rb:516:in `coerce_other'
/Users/w/.rbenv/versions/2.2.0/lib/ruby/2.2.0/ipaddr.rb:150:in `=='
schema_plus (1.8.4) lib/schema_plus/active_record/attribute.rb:12:in `original_value_with_schema_plus'
activerecord (4.2.0) lib/active_record/attribute.rb:37:in `value'
activerecord (4.2.0) lib/active_record/attribute.rb:46:in `value_for_database'
activerecord (4.2.0) lib/active_record/attribute_methods/dirty.rb:164:in `store_original_raw_attribute'
activerecord (4.2.0) lib/active_record/attribute_methods/dirty.rb:93:in `write_attribute'
activerecord (4.2.0) lib/active_record/attribute_methods.rb:50:in `__temp__c6163747f5379676e6f596e6f59607'
devise (3.4.1) lib/devise/models/trackable.rb:24:in `update_tracked_fields'
devise (3.4.1) lib/devise/models/trackable.rb:32:in `update_tracked_fields!'
devise (3.4.1) lib/devise/hooks/trackable.rb:7:in `block in <top (required)>'
warden (1.2.3) lib/warden/hooks.rb:14:in `call'
warden (1.2.3) lib/warden/hooks.rb:14:in `block in _run_callbacks'
warden (1.2.3) lib/warden/hooks.rb:9:in `each'
warden (1.2.3) lib/warden/hooks.rb:9:in `_run_callbacks'
warden (1.2.3) lib/warden/manager.rb:53:in `_run_callbacks'
warden (1.2.3) lib/warden/proxy.rb:179:in `set_user'
warden (1.2.3) lib/warden/proxy.rb:323:in `_perform_authentication'
warden (1.2.3) lib/warden/proxy.rb:127:in `authenticate!'
````

The error goes away and I am able to login & interact with the development environment when I remove schema_plus from my Gemfile. 

Also interestingly, I've not been able to reproduce these errors in my integration tests -- Capybara tests log in just fine. But it's as if something in my database has killed the development environment with respect to schema_plus.

Thanks for any thoughts. I'm a long-time user of SP for index and foreign key management but was wondering if there might be any incompatibilities between the latest versions of Rails/PG.

**Comment by lawso017** [comment]
On closer examination it looks like it may be related to an interaction between SP's managing default values, and Devise's "trackable" module which is attempting to store the ip address of my local machine which is defined as an "inet" field in the database. There is no default value specified for that field in the migration that created it however.

I can disable the "trackable" module to also get around the error. However, "trackable" plus SchemaPlus is not working at this point.

**Comment by ronen** [comment]
@lawso017 Sorry for the trouble, and thanks for the detailed investigation.

Looking at the code, it seems like the error you got could arise in some situations with integer columns.  But I haven't been able to recreate the error in the specs.  Before I try building a new app with devise & tracking, could you send me the schema dump definition for the table in question?

In any case, looking at the code, I could see a likely problem and have pushed a possible fix.  Since I haven't reproduced the error I can't say for sure that my change will actually fix it.  Can you try out the 1.x branch?

**Comment by lawso017** [comment]
Here is the Users table [pretty standard Devise setup]:

````
  create_table "users", force: :cascade do |t|
    t.string   "email",                  limit: 255, default: "",    null: false
    t.string   "encrypted_password",     limit: 255, default: ""
    t.string   "reset_password_token",   limit: 255
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",                      default: 0,     null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet     "current_sign_in_ip"
    t.inet     "last_sign_in_ip"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name",                   limit: 255,                 null: false
    t.index ["email"], :name => "index_users_on_email", :unique => true
    t.index ["name"], :name => "index_users_on_name", :case_sensitive => false
    t.index ["reset_password_token"], :name => "index_users_on_reset_password_token", :unique => true
  end
````

That change looks promising. Going to try it now...

**Comment by lawso017** [comment]
Yep, the object.equal? did the trick.

It's been a while since I've looked into the schema_plus repo (since it just works) :-) and just wanted to say thanks for the refactoring you're pursuing in the 2.0 branch. Will help to reduce complexity. Thanks again!

**Comment by lawso017** [comment]
Just curious... what issue was fixed by this commit?

https://github.com/SchemaPlus/schema_plus/commit/f50d8ebe6d910cee75b608317138ac7f13b4178b#diff-0

Trying to understand why it was necessary to alias_method_chain for AR's attribute.original_value. 

I'd rather avoid doing that if possible and am wondering if I can live without it.

**Comment by ronen** [comment]
@lawso017 

> what issue was fixed by this commit?

Yeah, not much of a comment on that commit.  It wasn't a separate formal issue, it was all part of getting schema_plus working with rails 4.2.  In order to get `DB_DEFAULT` to work, you have to somehow end-run around rails's tendency to do type conversion when you assign values to attributes, so that the bit which generates the actual SQL query can recognize DB_DEFAULT and substitute in the SQL keyword DEFAULT instead of a number, quoted value, or nothing.

> I'd rather avoid doing that if possible and am wondering if I can live without it.

There may be a more elegant way to do it.  Frankly I didn't take the time to deeply understand what ActiveRecord is doing in its type conversion, I just stepped through the execution until I found a spot where DB_DEFAULT was getting removed, and hacked around it.

> So I'm really glad you're modularizing SP's functionality in the 2.0 refactoring -- being just able to use the desired functionality to minimize complexity and extra cycles will be a big win.

Thanks, yeah me too :)

Though there'll be a certain constant overhead:  A core idea of the refactor is to push all the monkey patching into a "schema_monkey" gem which defines an extension API which the other gems can use.  (Then as rails changes, schema_monkey can adapt its monkey patching as needed but attempt to keep the API constant.)  Not all gems will use all calls in the API.  But the API itself is still there, wrapping many AR methods in a middleware callback mechanism, which will add a few cycles to each.

Dang, you make me wonder whether `schema_monkey` itself should be split into `schema_model_monkey` that only adds API for migrations and model-level queries (presumably rare) and `schema_record_monkey` that adds API for save/load of records.  So if you use no gems that affect save/load, you won't get the record API pulled in so won't need to pay for it.

Though I'm hoping that, considering the amount of stuff already going on when you save/load a record in ActiveRecord, the API will add only epsilon more.

Anyway, thanks for the interest!  If you'd like to take a more active part in all this, I'm always happy to have collaborators :)

Oh, and I've pushed out v1.8.5 with this fix in it.
