### ISSUE TITLE
Is it possible define foreign key constraints in tables between databases ?

### ISSUE THREAD

**Issue by bl4ckn0de** [SchemaPlus/schema_plus#202]
i have two databases defined in one app, one is legacy from an old app.

i don't like to copy the tables from the legacy database to the application database (only last resort), it's posible that schema_plus support this foreign key ?

**Comment by ronen** [comment]
Yes, you should be able to specify, e.g.:
 
```ruby
t.integer :thing_id, :foreign_key => { references: "other_database.things" }
```

**Comment by tovodeverett** [comment]
I don't know if Postgres supports this, but I suspect it does not.  I know MSSQL does not.  The problem is that each database is an independently restorable entity.  What happens when you restore one database back to a version that predates the other?  Suddenly the foreign key relationship may be inconsistent.

In general, when faced with this situation I have followed the advice in http://stackoverflow.com/a/4452586/1795300 - I keep a table in the foreign key databases that contains only the primary keys of the table in the primary key database, and then use triggers in the primary key database to maintain the table in the foreign key database.  You have to be careful with restores, though.
