### ISSUE TITLE
schema_plus schema:dump picks the first attribute from a composite primary key as the only primary key

### ISSUE THREAD

**Issue by kjg** [SchemaPlus/schema_plus#207]
if I `execute 'ALTER TABLE my_table  ADD PRIMARY KEY (one,  two)'`

The dump looks like

```
create_table "my_table", primary_key: "one", force: true do |t|
```

**Comment by ronen** [comment]
@kjg Thanks for the bug report -- but that's Rails' behavior, not schema_plus.  ActiveRecord doesn't support composite primary keys, and schema_plus doesn't do anything to support them either.  

There's a gem https://github.com/composite-primary-keys/composite_primary_keys, but I don't know anything about it.  Looking at its README it doesn't seem to address migrations and dumps. 

One could imagine that https://github.com/SchemaPlus/schema_plus_tables could be extended to detect composite primary keys and issue `primary_key: ["one", "two"]` in the dump -- but I think it would also need to extend `create_table` to accept an array of columns for `primary_key:` since AFAIK the option only accepts a single column.   If you'd like you can open an issue there with the feature request.  (I myself probably won't have time to get to it any time soon, but maybe somebody will see it and be motivated...  or you could try to implement it yourself...)

**Comment by kjg** [comment]
Thank you so much for the detailed response. I will open a feature request on SchemaPlus/schema_plus_tables. If I feel motivated enough, I might try to tackle it as well.

**Comment by ronen** [comment]
@kjg sounds good -- if you do decide to tackle it feel free to ask if you've got any questions or trouble with it.
