### ISSUE TITLE
How to I set this up on my Rails App? 

### ISSUE THREAD

**Issue by zwarburg** [SchemaPlus/schema_plus#208]
There is documentation about migrating from Automatic Foreign Key but if I install the gem how do I get it to actually run?

**Comment by ronen** [comment]
@zwarburg just include it your Gemfile:

```ruby
gem "schema_plus"
```

You don't need to do anything else, it will automatically set itself up as part of the rails initialization process.

**Comment by zwarburg** [comment]
@ronen then how do I configure it? I don't understand how to get the foreign keys to actually generate. I'm sorry, I'm sure this is a ridiculously stupid question.

**Comment by ronen** [comment]
The foreign keys are generated as part of Rails migrations.  In a migration, if you create a column, e.g.:

```ruby
change_table "whatevers" do |t|
  # any one of these
  t.references "things"
  t.belongs_to "things"
  t.integer "thing_id"
end
```

then schema_plus will by default automatically define the corresponding foreign key constraint.    Details in the README.

If you already have the schema defined from before you were using schema_plus, and you now want to add foreign key constraints, you'd need to set up a migration that just adds the foreign key

```ruby
change_table "whatevers" do |t|
  t.foreign_key :thing_id, "things", "id"
end

# or

add_foreign_key "whatevers", "thing_id", "things", "id"
```
the documentation is unfortunately minimal and a bit hidden (that will be fixed in schema_plus 2.0 which is under development), but it's at:

* http://www.rubydoc.info/gems/schema_plus/SchemaPlus/ActiveRecord/ConnectionAdapters/AbstractAdapter:add_foreign_key
* http://www.rubydoc.info/gems/schema_plus/SchemaPlus/ActiveRecord/ConnectionAdapters/TableDefinition:foreign_key

**Comment by zwarburg** [comment]
@ronen THANK YOU VERY much for taking the time to write me a detailed response. I really do appreciate it. All to often I find that my n00b questions go unanswered because people feel I should know the answer. Really is appreciated that you took the time to write a detailed explanation. Thank you again!

**Comment by ronen** [comment]
no prob.  hope schema_plus is useful to you!
