### ISSUE TITLE
Schema dump support for multiple schemas

### ISSUE THREAD

**Issue by stenver** [SchemaPlus/schema_plus#219]
What do you guys think of adding support for multiple schemas in the schema dump. The way it would work is instead of exporting 
```create_table 'table_name' ``` 
in schema.rb, it would 
```create_table 'schema.table_name'```
This could be figured with some configuration flag.

I would be happy to work on this PR myself if you guys think its a good idea. If not, please let me know why not.

**Comment by ronen** [comment]
@stenver  sounds fine to me.  Go for it!

Now that schema_plus is a collection of smaller feature gems, I'm thinking this could be done in its own gem.  I.e. rather than a configuration flag, a user would simply choose to include "schema_plus_multischema" (or whatever it'd be called) which would add that capability.

[schema_plus_core](https://github.com/SchemaPlus/schema_plus_core) provides hooks into the dumping mechanism (see the [Dumper section of the README](https://github.com/SchemaPlus/schema_plus_core#dumper) -- though that doc is awfully terse; PR's to improve it would be welcome!).  I haven't thought through whether those hooks are sufficient to add multiple schema support -- if we're lucky they are and your gem will be fairly simple (is it sufficient to have middleware that changes `table.pname` from `"table_name"` to `"schema.table_name"`?).  If not, maybe the thing to do would be to augment those hooks -- so that your gem would still be fairly simple.

Does that seem reasonable? Happy to explain more (especially the possibly opaque Dumper hooks).

Oh, and I'd be happy to give you appropriate access to put the gem in the SchemaPlus github organization.

**Comment by stenver** [comment]
Thanks Ronen, sounds great!

I took a brief look at the schema core, it seemed simple enough. If i get any questions, i will let you know.

I would be grateful for the appropriate access. I can start working on the gem in the next few days as a cool side-project :)

**Comment by stenver** [comment]
Hei @ronen. Sorry for such a late response on this.

For starters, this gem is going to be for postgres.

I have looked around the code a lot and started to write my gem. My searches have led me all the way to the ```schema_plus_core```. 

Basically, am I reading this right that the tables created by Schema Plus are not from the SQL, but from [activerecord tables](https://github.com/SchemaPlus/schema_plus_core/blob/master/lib/schema_plus/core/active_record/schema_dumper.rb#L48)?

I found out that the ```env``` variable [doesnt hold any information regarding schemas](https://github.com/SchemaPlus/schema_plus_core/blob/master/lib/schema_plus/core/middleware.rb#L69), so I cannot change a table name. I was hoping to modify ```schema_plus_core``` to add ```schema``` to the [tables](https://github.com/SchemaPlus/schema_plus_core/blob/master/lib/schema_plus/core/schema_dump.rb#L46), but if the tables are read from active record strings then that solution is probably not feasible.


Am I correct that the only solution I have atm is to create a connection adapter which requests table schema by table name? If so, any ideas what to do if I have 2 tables in different schemas with the same name.

**Comment by ronen** [comment]
Hi @stenver 

> am I reading this right that the tables created by Schema Plus are not from the SQL, but from activerecord tables?

Yes, SchemaPlus's dumper intercepts ActiveRecord's dump and parses the string.  Ugly hack, but didn't want to duplicate the existing dumping code.

> Am I correct that the only solution I have atm is to create a connection adapter which requests table schema by table name?

I guess it depends what you're trying to do...  ActiveRecord dumps all tables that are returned by `@connection.tables`.  My understanding is that it will include all tables in the current/default schema (except for any that you might have added to the `ActiveRecord::SchemaDumper.ignore_tables`).

If you want to support dumping tables from schemas other than the current default, I think you'd need to modify the connection adapter's `tables` method to query those schemas.  That method currently returns each table name as a string, so maybe you could change it to return `schema_name.table_name` for each?

**Comment by stenver** [comment]
Hei @ronen 

Thanks for the help! I got the gem working and tests passing. Can you please create the repository, so i could make a PR? I dont have privileges to create a repository myself.

**Comment by ronen** [comment]
@stenver I've created https://github.com/SchemaPlus/schema_plus_multischema, and made you a collaborator on it.
