### ISSUE TITLE
Schema plus schema dump crashes on custom types on postgresql

### ISSUE THREAD

**Issue by stenver** [SchemaPlus/schema_plus#224]
If your database has defined custom types, then schema_plus crashes when doing schema_dump

```SQL
CREATE TYPE my_type AS ENUM (
    'a',
    'b'
);

CREATE TABLE my_table (
    my_column my_type DEFAULT 'a'::my_type NOT NULL
);

```
The crashing line is [here](https://github.com/SchemaPlus/schema_plus_core/blob/master/lib/schema_plus/core/active_record/schema_dumper.rb#L63)

```stream.string``` contains:
```
"# Could not dump table \"my_table\" because of following StandardError\n#   Unknown type 'my_type' for column 'my_column'\n\n"
```
An easy dirty fix is to return, if m is nil. I can do the PR, if you approve this fix. The downside is that no warning is displayed to the user that one of the tables is completely left out from the dump. I could also make it so it displays a warning message if this happens. The warning message could contain whatever ```stream.string``` contains.

If that result is undesired, then another option would be to just raise whatever error calling super raises, because that way the user will at least get an error message

**Comment by ronen** [comment]
Thanks for finding this and tracking it down.  The desired behavior for schema_plus_core is to continue to include that string in the dump, following the principle that schema_plus_core doesn't change behavior.

And thanks for offering to do a PR... I thought about how to get that desired behavior and it seemed easiest to code it up myself rather than describe it and ask you to do it.  So I did (if you're curious, see [this commit](https://github.com/SchemaPlus/schema_plus_core/commit/205a3b16b484e95cf9b0999e8eea1f8b5cd88ef3)), and have released schema_plus_core v0.6.0

**Comment by ronen** [comment]
BTW it still seems pretty sucky to dump an error message rather than the table.  One quick solution could be to add middleware (probably in schema_plus_tables) to replace the error message with a raw SQL dump.  Though that SQL would probably fail to execute because the dump wouldn't include the custom data type definition.   Better of course would be to actually add support for custom data types

**Comment by stenver** [comment]
Probably a gem to add support to custom types would be the best course of action. That way the user of this gem wont have any unexpected surprises when using schema plus and then just losing tables. I guess, the first iteration could have raw sql dump the custom types and tables to just have something.

**Comment by stenver** [comment]
I will try to find time to work on this gem in the near future

**Comment by ronen** [comment]
@stenver closing this out for now.  would still be happy to see such a gem...
